"""
Django settings for devbrain_project project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env (backend/.env) for local runs; in Docker/cloud these come from
# real environment variables instead, which load_dotenv() won't override.
load_dotenv(BASE_DIR / '.env')


# --- Core security settings — all overridable via environment variables ---

# SECURITY WARNING: keep the secret key used in production secret!
# Falls back to an insecure dev key so local `runserver` still works out of
# the box, but ALWAYS set a real SECRET_KEY env var in any deployed env.
SECRET_KEY = os.getenv(
    'SECRET_KEY',
    'django-insecure-(k15-sgqc_1hu$sh+8m*s%80-(thqntl(-14oq88yd_ej6@1gn',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False now (safe default); set DEBUG=True in your local .env.
DEBUG = os.getenv('DEBUG', 'False').strip().lower() == 'true'

# Comma-separated list, e.g. ALLOWED_HOSTS=myapp.onrender.com,myapp.up.railway.app
_allowed_hosts = os.getenv('ALLOWED_HOSTS', '')
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts.split(',') if h.strip()]
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1']
# Render sets this automatically — pick it up so you don't have to.
_render_host = os.getenv('RENDER_EXTERNAL_HOSTNAME')
if _render_host and _render_host not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_render_host)
if not ALLOWED_HOSTS:
    # Last-resort fallback so a missing env var doesn't hard-crash every
    # request with Django's DisallowedHost error — but you should still set
    # ALLOWED_HOSTS explicitly for real deployments.
    ALLOWED_HOSTS = ['*']

# Needed alongside ALLOWED_HOSTS for POST requests (admin, ingest) once the
# app sits behind HTTPS on a cloud domain.
_csrf_origins = os.getenv('CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_origins.split(',') if o.strip()]
if _render_host:
    CSRF_TRUSTED_ORIGINS.append(f'https://{_render_host}')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'brain_app',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'devbrain_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / '..' / 'frontend' / 'dist'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'devbrain_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# Defaults to SQLite (fine for personal/local use — note SQLite lives on
# local disk, so on most free-tier cloud hosts it resets on every redeploy
# unless you attach a persistent volume). Set DATABASE_URL to use Postgres
# instead (e.g. the free Postgres add-on on Render/Railway).

import dj_database_url

DATABASE_URL = os.getenv('DATABASE_URL')
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    }
else:
    _sqlite_dir = BASE_DIR / 'dbdata'
    _sqlite_dir.mkdir(parents=True, exist_ok=True)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': _sqlite_dir / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
_frontend_dist = BASE_DIR / '..' / 'frontend' / 'dist'
STATICFILES_DIRS = [_frontend_dist] if _frontend_dist.exists() else []
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise serves STATIC_ROOT directly from the app process — required
# because Django's own dev-server static handling is disabled once
# DEBUG=False, which would otherwise leave the deployed UI unstyled/blank.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Comma-separated list, e.g. CORS_ALLOWED_ORIGINS=https://myapp.vercel.app
_cors_origins = os.getenv('CORS_ALLOWED_ORIGINS', '')
CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_origins.split(',') if o.strip()]
# Default to permissive CORS only when nothing is configured — fine since
# the frontend is same-origin (served by this same Django app) in the
# standard deployment; tighten this if you split the frontend out.
CORS_ALLOW_ALL_ORIGINS = not CORS_ALLOWED_ORIGINS

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
